### PR TITLE
add documentation for ncio library

### PR DESCRIPTION
**Pull request by Hang-Lei-NOAA**
We compiled and added the documentation based on the doxygen added into the NCEPLIBS-ncio repo.

### CODE REVIEW

**Review by MinsukJi-NOAA — COMMENTED** [review]
The section "user_guide" is a blank page: https://hang-lei-noaa.github.io/NCEPLIBS/NCEPLIBS-ncio/html/md__home_Hang_8Lei_noscrub_NCEPLIBS-ncio_docs_user_guide.html. Is it for future revisions? I think it would be nice to have at least a sentence or a link.

In the 'API' section, is it a common convention to use ! as a delimiter?: https://hang-lei-noaa.github.io/NCEPLIBS/NCEPLIBS-ncio/html/index.html

**Comment by Hang-Lei-NOAA** [comment]
This text has been reorganized. Please review. Thanks

**Comment by MinsukJi-NOAA** [comment]
@Hang-Lei-NOAA thanks for addressing some of the issues raised in the previous review.
- [Front page](https://hang-lei-noaa.github.io/NCEPLIBS/NCEPLIBS-ncio/html/) looks good
- Somehow [this page](https://hang-lei-noaa.github.io/NCEPLIBS/NCEPLIBS-ncio/html/md__home_Hang_8Lei_noscrub_NCEPLIBS-ncio_docs_Main.html) is still blank
- On [this page](https://hang-lei-noaa.github.io/NCEPLIBS/NCEPLIBS-ncio/html/md__home_Hang_8Lei_noscrub_NCEPLIBS-ncio_docs_user_guide.html), some bullet points have empty lines. Also, some of them start with ! and some don't.

**Comment by Hang-Lei-NOAA** [comment]
Hi Minsuk

The main is the source of the main page. Do you know how to unshow it?
Start with ! is normal, that we want it not too long for a single line.

**Comment by Hang-Lei-NOAA** [comment]
I got these empty lines removed.
The main is the source of the main page. not changed

**Review by MinsukJi-NOAA — APPROVED** [review]
Hang, I am not sure how to hide the main at the moment. I approve this PR as it is.

**Comment by Hang-Lei-NOAA** [comment]
Thanks, what is the next step for this. Perhaps, Jun could merge.

**Pull request merged**
