### PR TITLE
remove all static documentation from this repository

### PR DESCRIPTION
**Pull request by aerorahul**
None of these files belong in this repository.
They belong with the code that generated them.
At best a page to link to those is needed.

### CODE REVIEW

**Comment by MinsukJi-NOAA** [comment]
FV3_Dycore and NEMS ufs-v* may have external links from the UFS public release documentation.

**Comment by aerorahul** [comment]
> FV3_Dycore and NEMS ufs-v* may have external links from the UFS public release documentation.

Please ask them to update their docs.

**Comment by MinsukJi-NOAA** [comment]
So, all the links [here](https://github.com/NOAA-EMC/NOAA-EMC.github.io/blob/master/index.html) will be gone? And the new links will be https://noaa-emc.github.io/NEMS/ for NEMS and https://noaa-emc.github.io/FV3_dycore/ for FV3_dycore? The sources for the latter are [here](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere). Maybe we won't have FV3_dycore documentation here any longer.

**Comment by arunchawla-NOAA** [comment]
I am reaching out to Ligia to see where the public release documentation links were hosted

**Review by arunchawla-NOAA — APPROVED** [review]
Since these are html files that were generated from doxygen files then they can be removed. If needed the html files can be generated again from the doxygen files and then placed in the appropriate places in the repos

**Review by Hang-Lei-NOAA — APPROVED** [review]

**Review by MinsukJi-NOAA — APPROVED** [review]

**Comment by arunchawla-NOAA** [comment]
@aerorahul since the versioned documentation (NEMS and FV3 v 1.0.0, v1.1.0 and v 1.2.0) have been released to the community and these links been broadcast far and wide, at this moment can we not remove these directories. Everything else should be removed

**Comment by aerorahul** [comment]
Closing this PR.
Will re-open with a subset of these retained.

**Pull request closed without merging**
